### ISSUE TITLE
Add "Tab" and "Shift+Tab" to datekeys directive

### ISSUE THREAD

**Issue by danizen** [joeeames/AngularFundamentalsFiles#28]
For accessibility, probably good to add navigational keys 9 and 16 to the app/js/directives/datekeys.js
That's what I did.

**Comment by joeeames** [comment]
that's absolutely a good idea. I often spend a lot of time debating in a course whether to just teach the listed topic, or to teach it "right". You should put in accessibility in your apps. But you should also put in tests, internationalization, other accessibility issues (like zoom support for poor eyesight, which is far more common than a need for keyboard support), refactoring, etc. In the end, I choose to ignore all the "good practices" and just focus on the content that I'm teaching, and leave the topics of accessibility to other courses. It's not ideal. I truly agree with that. But it adds noise when someone just wants to learn the specific topic. I should do a better job discussing this matter at the beginning of my courses so that people know where I stand, and why I choose not to show these items. 

Thank you Dan for taking the time to post here. I appreciate it. I'll close the issue since there's nothing actionable I can do here.
